# Basic of Tensorflow Tensors

* Tensors
* Getting info from tensors
* Manipulating tensors
* Tensors and Numpy
* @tf.function for speeding up python code
* Using GPU
* Exersises 

ctrl + shift + space for func info


* scalar has 0 dimansion (single number)
* vector has 1 dimansion (has a direction)
* matrix has 2 dimansions
* tensor has > 2 dimansions

### Creating basic tensor data 

In [1]:
import tensorflow as tf
print(tf.__version__)
import numpy as np

2.6.0


In [2]:
# Create tensors as tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check number of dimensions of a tensor
scalar.ndim

0

In [4]:
# Create vector

vector = tf.constant([10, 10])
print(vector)
print(vector.ndim)

tf.Tensor([10 10], shape=(2,), dtype=int32)
1


In [5]:
# Create matix (has more than one dim)

matrix = tf.constant([[10, 7], [7, 10]])

print(matrix)
print(matrix.ndim)


tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
2


In [6]:
# Create a tensor

tensor = tf.constant([[[1, 2, 3], 
                       [1,2,3]],
                       [[1,2,3], 
                        [3,4,5]], 
                      [[3,4,5], 
                       [3,4,5]]])

print(f"{tensor}, number of dims {tensor.ndim}")

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [3 4 5]]

 [[3 4 5]
  [3 4 5]]], number of dims 3


In [7]:
# Creating tensor with tf.Variable()
changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])

changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [8]:
# Changing elements
changable_tensor[0].assign(7)
changable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

##### tf.Variable we can make changing in the values 

### Creating random tensors
Random tensors are tensors of some abitrary size which contain random numbers.

e.g. weights are random initialized numbers (well not exactly normal distribution/ glorify etc...)

from_seed is giving extra x value so everything using the 42 if going to be the same


In [9]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [10]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [11]:
tf.reduce_mean(random_1), tf.reduce_mean(random_2)

(<tf.Tensor: shape=(), dtype=float32, numpy=-0.6748808>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-0.6748808>)

### Shuffle order of elements in tensor/

In [12]:
not_shuffled = tf.constant([[10,7],
                            [3, 4],
                            [2, 3]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  3]], dtype=int32)>

In [13]:
shuffled = tf.random.shuffle(not_shuffled, seed=42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  3],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [14]:
tf.random.set_seed(7)
tf.random.shuffle(not_shuffled, seed=7)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  3]], dtype=int32)>

When you initialize a global seed (tf.random.set_seed(42)) and you pass that to the operation seed in the function, it uses the global state of X param.

Thats how if we want ouf shuffled tensors to be in the same order, we have ti use global seed

### Other ways to create tensors

In [15]:
tf.ones([2, 4]), tf.zeros([2, 4])

(<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32)>)

Turn Numpy array into tensors.

The main difference between NumPy arrays and Tensorflow tensors is that tensors can be run on GPU

In [16]:
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A, numpy_A.shape

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32), (24,))

In [17]:
tf.constant(numpy_A, shape=(2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

!!!! numpy_A shape is 24 and the dims 2*3*4 = 24 in order to work

### Getting infos from Tensors

* Shape - The length of each of dimensions of tensor - .shape
* Rank - Nuber of dims - .ndim
* Axis of dimesnion - a particular dimension of tensor - tensor[0], tensor[:, 1]
* Size - Total number of items in tensor - tf.size(tensor)

In [48]:
# Create a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [49]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [50]:
2*3*4*5

120

In [51]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dims:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dims: 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: 120


#### Index tensors

Tensors can be indexed like Python lists.

In [52]:
# Get the first 2 elements of each dim

rank_4_tensor[:, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [53]:
# Get the first element from each dim from each index except final one

rank_4_tensor[:1, :1, :, :]

<tf.Tensor: shape=(1, 1, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [54]:
rank_2_tensor = tf.constant([[2,4], [15,16]])

# Get last item of each of our 2 rank tensor

rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 4, 16], dtype=int32)>

In [55]:
# ADD in extra dim from rank 2 to rank 3 tensor
## ... means every axis before to be the same
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 2],
        [ 4]],

       [[15],
        [16]]], dtype=int32)>

In [56]:
tf.expand_dims(rank_2_tensor, axis=-1) # -1 because of the last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 2],
        [ 4]],

       [[15],
        [16]]], dtype=int32)>

### Tensor Manipulation (tensor operations)

** Basic operations**
`+`, `-`, `*`, `/`

In [37]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [39]:
tensor * 10, tensor/10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[1. , 0.7],
        [0.3, 0.4]])>)

In [40]:
# We can use the tf built-in funcs too

tf.math.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matix multiplication**

In ML this is one of the most common tensor operations

There are two rules our tensors need to fultil if we're going to matix multiply them: 

1. The inner dims must match e.g (3 x 4) * (4 x 5)
2. The resulting matrix has the shape of the inner dimensions

In [41]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [43]:
# in python me have different operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [57]:
tensor * tensor[..., tf.newaxis]

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[100,  70],
        [ 21,  28]],

       [[ 30,  21],
        [ 12,  16]]], dtype=int32)>

In [63]:
X = tf.Variable([[1,2], [3, 4], [5, 6]])
Y = tf.Variable([[7,8], [9, 10], [11, 12]])

In [64]:
X, Y

(<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [65]:
# tf.matmul(X, Y) is going to give me an error beacuse it not following the rule of matrix multiplication

In [67]:
Y_reshaped = tf.reshape(Y, shape=(2, 3))
Y_reshaped

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [68]:
tf.matmul(X, Y_reshaped)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [78]:
# Can do th same with transose
print("Original X:", X), print("Trnasposed X:",tf.transpose(X)), print("Reshaped X:", tf.reshape(X, shape=(2,3)))

Original X: <tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>
Trnasposed X: tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)
Reshaped X: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


(None, None, None)

Diffenrence between tf. transpose and tf.reshape is that:
1. tf.transpose flip the axis and from (3,2) it is (2, 3)
2. tf.reshape it shuffle the tensor so it can geto to the needed shape


In [71]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

### Aggregating tensors

Aggregation tensors = condensing them from mltiple values down to a smaller amount of values

min, max, mean, sum of tensor

In [81]:
# Get the absolute values
D = tf.constant([-7, -10])
D, tf.abs(D)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

In [99]:
E = tf.Variable(np.random.randint(0,100, size = (3,2)), shape=(3, 2))
E

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int64, numpy=
array([[75, 96],
       [88, 17],
       [81, 43]])>

In [102]:
print("Min:",tf.reduce_min(E).numpy()) 
print("Max:", tf.reduce_max(E).numpy())
print("Mean:", tf.reduce_mean(E).numpy()) 
print("Sum:", tf.reduce_sum(E).numpy()) 

Min: 17
Max: 96
Mean: 66
Sum: 400


In [117]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=769.5>

In [118]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=27.73>

### Find the positional maximum and minimum 

For each column to find its max and min

In [119]:
tf.random.set_seed(42)

F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [120]:
# Find positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [124]:
# Index of out largest value position
F[tf.argmax(F)], tf.reduce_max(F)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [127]:
tf.argmax(tf.reshape(F, shape=(5, 10)))

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([3, 4, 4, 2, 4, 1, 3, 0, 2, 3])>

### Squeezing a tensor (removing all single dims) and one-hot encode

In [131]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [134]:
tf.squeeze(G)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [141]:
n = [1,2,3,4]

tf.one_hot(n, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [146]:
H = tf.range(1,10, dtype = tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [147]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([ 1.,  4.,  9., 16., 25., 36., 49., 64., 81.], dtype=float32)>

In [149]:
tf.math.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [150]:
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>